version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./_volume/rabbitmq/data/:/var/lib/rabbitmq/
      # - ./_volume/log/:/var/log/rabbitmq
  frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "0.0.0.0:8081:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./_volume/registry:/data
  app:
    image: image-builder:latest
    # network_mode: host
    env_file:
      - .env
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - registry
